// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LumoTrack.App.iOS
{
	public partial class NotificationTableView : UITableView
	{
		public NotificationTableView (IntPtr handle) : base (handle)
		{
		}
	}
}
