// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LumoTrack.App.iOS
{
	public partial class NavigationViewController : UINavigationController
	{
		public NavigationViewController (IntPtr handle) : base (handle)
		{

		}


        public override UIStatusBarStyle PreferredStatusBarStyle()
        {
            return UIStatusBarStyle.Default;
        }


    }
}
