// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LumoTrack.App.iOS
{
	public partial class InboxViewCell : UITableViewCell
	{
		public InboxViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
